---
- name: Create user 'test1' and set a password
  hosts: your_target_group_name
  become: yes

  vars:
    # Set the plaintext password here. 
    # For better security, consider moving this to a vault file.
    user_password: "Pa$$w0rd"

  tasks:
    - name: Set up the hashed password
      ansible.builtin.set_fact:
        hashed_password: "{{ user_password | password_hash('sha512') }}"

    - name: Ensure user 'test1' is present with the hashed password
      ansible.builtin.user:
        name: test1
        state: present
        comment: "Automated User Creation"
        shell: /bin/bash
        home: /home/test1
        # Use the securely generated hash
        password: "{{ hashed_password }}"
        # Ensure the user's password expires after creation (forces them to change it on first login)
        update_password: on_create
